// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types'
import type { GenericContractEvents, GenericContractEvent } from 'dedot/contracts'

export interface ContractEvents<ChainApi extends GenericSubstrateApi>
  extends GenericContractEvents<ChainApi> {
  /**
   *
   * @signature_topic: 0x096bb2d50ce5aa43ab85a5681d5e8498e69e9fba99c0e016e6dfe3a2236e62ab
   **/
  Success: GenericContractEvent<
    'Success',
    {
      /**
       *
       * @indexed: false
       **/
      id: bigint
      /**
       *
       * @indexed: false
       **/
      price: bigint
    }
  >
}
