// Generated by dedot cli

import type { AccountId32 } from 'dedot/codecs'

export type InkStorageLazyMapping = {}

export type InkStorageTraitsImplsResolverKey = {}

export type InkStorageTraitsImplsAutoKey = {}

export type InkStorageTraitsImplsManualKey = {}

export type WasmRegistrationProxy = {
  admin: AccountId32
  pendingAdmin?: AccountId32 | undefined
  registryAddr: AccountId32
  controllers: InkStorageLazyMapping
  usedIds: InkStorageLazyMapping
}

export type InkPrimitivesLangError = 'CouldNotReadInput'

export type WasmRegistrationProxyError =
  | { type: 'NotAdmin' }
  | { type: 'NotController' }
  | { type: 'InsufficientBalance' }
  | { type: 'TooExpensive' }
  | { type: 'DuplicateId' }
  | { type: 'RegisterFailed'; value: number }
  | { type: 'PriceFetchFailed'; value: number }

export type WasmRegistrationProxyInnerResult =
  | { type: 'Pass'; value: bigint }
  | { type: 'Fail'; value: WasmRegistrationProxyError }

export type InkEnvNoChainExtension = null
